name: Build Package

on: 
  push:
    tags: [ '*' ]

jobs:
  rpm:
    runs-on: ubuntu-latest

    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - name: fpm
      run: gem install fpm -v 1.11.0

    - name: deps
      run: |
        sudo add-apt-repository -y ppa:ondrej/apache2
        sudo apt install -y build-essential bison flex libaprutil1-dev rpm

    - uses: actions/checkout@v3
    - name: autogen
      run: ./autogen.sh && mkdir -p packages/

    - name: make rpm
      run: make rpm && cp *.rpm packages/

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          packages/*.rpm

  python:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ '3.6', '3.8', '3.10' ]

    steps:
    - name: deps
      run: |
        sudo add-apt-repository -y ppa:ondrej/apache2
        sudo apt install -y python3-dev build-essential bison flex libaprutil1-dev swig

    - uses: actions/checkout@v3
    - name: autogen
      run: ./autogen.sh && mkdir -p packages/

    - name: make install
      run: make && sudo make install

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install setuptools

    - name: make python-rpm
      run: make python-rpm && cp bindings/python/dist/*.whl packages/

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          packages/*.whl
